services:
  app1:
    build:
      context: ./app1
    ports:
      - "8080:80"
    container_name: app1-nginx
    networks:
      - app-network

  app2:
    build:
      context: ./app2
    ports:
      - "8081:80"
    container_name: app2-httpd
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
